image: node:20.16.0

stages:
  - build_image

build_image:
  stage: build_image
  image: jdrouet/docker-with-buildx:stable
  dependencies:
    - build_frontend  # This ensures artifacts are downloaded
    - test_stage
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker buildx create --use
    - docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE:latest --platform linux/amd64 --tag $CI_REGISTRY_IMAGE:latest --push .
    # uncomment next line to build for ARM
    #- docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE:latest --platform linux/arm64/v8,linux/amd64 --tag $CI_REGISTRY_IMAGE:latest --push .
    # For tags: add -t $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}
#  only:
#    - tags