image: node:20.12.2

stages:
  - build_frontend
  - build_image

cache:
  paths:
    - node_modules/

build_frontend:
  stage: build_frontend
  script:
    - CI=true npm install
    - CI=true npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

build_image:
  stage: build_image
  image: docker:20.10.11
  services:
    - name: docker:20.10.11-dind
      alias: docker
  dependencies:
    - build_frontend  # This ensures artifacts are downloaded
  variables:
    # Enable Buildx and experimental features
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
  before_script:
    # Set up Docker Buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --name multiarch --use || true
    - docker buildx inspect --bootstrap
  script:
    - ls -la dist/  # Verify the dist folder is available
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    # Build for multiple platforms using buildx
    - |
      docker buildx build \
        --platform linux/amd64,linux/arm64/v8 \
        -t $CI_REGISTRY_IMAGE:latest \
        -t $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG} \
        --push \
        .
#  only:
#    - tags